Restaurant/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Restaurant.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Restaurant/Controllers/NamesController.cs
using Restaurant.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Restaurant.Controllers
{
    public class NamesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Names
        public ActionResult Index(int? page, string searchQuery)
        {
            ViewBag.SearchQuery = searchQuery;
            int pageSize = 2;// display three blog posts at a time on this page
            int pageNumber = (page ?? 1);
            var nameQuery = db.Names.OrderBy(p => p.RestaurantName).AsQueryable();
            if (!string.IsNullOrWhiteSpace(searchQuery))
                nameQuery = nameQuery.Where(p => p.RestaurantName.Contains(searchQuery)
                || p.Information.Contains(searchQuery)
                || p.UserId.Contains(searchQuery));
        }
        var name = nameQuery.ToPagedList(pageNumber, pageSize);
            return View(name);
    }

    // GET: Names/Details/5
    public ActionResult Details(int? id)
    {
        if (id == null)
        {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }
        Name name = db.Names.Find(id);
        if (name == null)
        {
            return HttpNotFound();
        }
        return View(name);
    }

    // GET: Names/Create
    public ActionResult Create()
    {
        ViewBag.UserId = new SelectList(db.Users, "Id", "Email");
        return View();
    }

    // POST: Names/Create
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create([Bind(Include = "Id,RestaurantName,Information,UserId")] Name name)
    {
        if (ModelState.IsValid)
        {
            db.Names.Add(name);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        ViewBag.UserId = new SelectList(db.Users, "Id", "Email", name.UserId);
        return View(name);
    }

    // GET: Names/Edit/5
    public ActionResult Edit(int? id)
    {
        if (id == null)
        {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }
        Name name = db.Names.Find(id);
        if (name == null)
        {
            return HttpNotFound();
        }
        ViewBag.UserId = new SelectList(db.Users, "Id", "Email", name.UserId);
        return View(name);
    }

    // POST: Names/Edit/5
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit([Bind(Include = "Id,RestaurantName,Information,UserId")] Name name)
    {
        if (ModelState.IsValid)
        {
            db.Entry(name).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        ViewBag.UserId = new SelectList(db.Users, "Id", "Email", name.UserId);
        return View(name);
    }

    // GET: Names/Delete/5
    public ActionResult Delete(int? id)
    {
        if (id == null)
        {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }
        Name name = db.Names.Find(id);
        if (name == null)
        {
            return HttpNotFound();
        }
        return View(name);
    }

    // POST: Names/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public ActionResult DeleteConfirmed(int id)
    {
        Name name = db.Names.Find(id);
        db.Names.Remove(name);
        db.SaveChanges();
        return RedirectToAction("Index");
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            db.Dispose();
        }
        base.Dispose(disposing);
    }
}
}

Restaurant/Controllers/TypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using Restaurant.Models;

namespace Restaurant.Controllers
{
    public class TypesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Types
        public ActionResult Index(int? page, string searchQuery)
        {
            ViewBag.SearchQuery = searchQuery;
            int pageSize = 2; // display three blog posts at a time on this page
            int pageNumber = (page ?? 1);
            var typeQuery = db.Types.OrderBy(p => p.RestaurantType).AsQueryable();
            if (!string.IsNullOrWhiteSpace(searchQuery))
            {
                typeQuery = typeQuery.Where(p => p.RestaurantType.Contains(searchQuery)
                || p.Comments.Contains(searchQuery)
                || p.UserId.Contains(searchQuery));
            }
            var type = typeQuery.ToPagedList(pageNumber, pageSize);
            return View(type);
        }

        // GET: Types/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Models.Type type = db.Types.Find(id);
            if (type == null)
            {
                return HttpNotFound();
            }
            return View(type);
        }

        // GET: Types/Create
        public ActionResult Create()
        {
            ViewBag.NameId = new SelectList(db.Names, "Id", "RestaurantName");
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email");
            return View();
        }

        // POST: Types/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,RestaurantType,Price,Comments,Ratings,NameId,UserId")] Models.Type type)
        {
            if (ModelState.IsValid)
            {
                db.Types.Add(type);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.NameId = new SelectList(db.Names, "Id", "RestaurantName", type.NameId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", type.UserId);
            return View(type);
        }

        // GET: Types/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Models.Type type = db.Types.Find(id);
            if (type == null)
            {
                return HttpNotFound();
            }
            ViewBag.NameId = new SelectList(db.Names, "Id", "RestaurantName", type.NameId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", type.UserId);
            return View(type);
        }

        // POST: Types/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,RestaurantType,Price,Comments,Ratings,NameId,UserId")] Models.Type type)
        {
            if (ModelState.IsValid)
            {
                db.Entry(type).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.NameId = new SelectList(db.Names, "Id", "RestaurantName", type.NameId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", type.UserId);
            return View(type);
        }

        // GET: Types/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Models.Type type = db.Types.Find(id);
            if (type == null)
            {
                return HttpNotFound();
            }
            return View(type);
        }

        // POST: Types/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Models.Type type = db.Types.Find(id);
            db.Types.Remove(type);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Restaurant/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Restaurant/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Restaurant/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Creative - Start Bootstrap Theme</title>
    <!-- Font Awesome Icons -->

    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css" />
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>
    <!-- Plugin CSS -->

    <link href="~/vendor/magnific-popup/magnific-popup.css" rel="stylesheet" />
    <!-- Theme CSS - Includes Bootstrap -->

    <link href="~/Content/creative.min.css" rel="stylesheet" />
</head>
<body id="page-top">
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="@Url.Action("Index","Home")">Application Name</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto my-2 my-lg-0">
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="@Url.Action("Register","Account")">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="@Url.Action("Login","Account")">Log in</a>
                    </li>
                   
                    @*<li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#portfolio">Portfolio</a>
        </li>
        <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
        </li>*@
                </ul>
                
            </div>
        </div>
    </nav>
    <!-- Masthead -->
    <header class="masthead">
        <div class="container h-100">
            <div class="row h-100 align-items-center justify-content-center text-center">
                <div class="col-lg-10 align-self-end">
                    <h1 class="text-uppercase text-white font-weight-bold">Your Favorite Restaurant</h1>
                    <hr class="divider my-4">
                </div>
                <div class="col-lg-8 align-self-baseline">
                    <p class="text-white-75 font-weight-light mb-5">Start Your favorite restaurant!</p>
                    <a class="btn btn-primary btn-xl js-scroll-trigger" href="@Url.Action("Index","Names")">Find Out More</a>
                </div>
            </div>
        </div>
    </header>
    <!-- About Section -->
    <section class="page-section bg-primary" id="about">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8 text-center">
                    <h2 class="text-white mt-0">Restaurant Menu</h2>
                    <hr class="divider light my-4">
                    <p class="text-white-50 mb-4">This is the restaurant menu!</p>
                    <a class="btn btn-light btn-xl js-scroll-trigger" href="@Url.Action("Index","Types")">Choose Menu</a>
                </div>
            </div>
        </div>
    </section>
   
  
    <!-- Portfolio Section -->
    <section id="portfolio">
        <div class="container-fluid p-0">
            <div class="row no-gutters">
                <div class="col-lg-4 col-sm-6">
                    <a class="portfolio-box" href="img/portfolio/fullsize/1.jpg">
                        
                        <img src="~/img/portfolio/thumbnails/1.jpg" alt=""/>
                        <div class="portfolio-box-caption">
                            <div class="project-category text-white-50">
                                Category
                            </div>
                            <div class="project-name">
                                Restaurant Name
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a class="portfolio-box" href="img/portfolio/fullsize/2.jpg">
                      
                        <img src="~/img/portfolio/thumbnails/2.jpg" alt=""/>
                        <div class="portfolio-box-caption">
                            <div class="project-category text-white-50">
                                Category
                            </div>
                            <div class="project-name">
                                Restaurant Name
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a class="portfolio-box" href="img/portfolio/fullsize/3.jpg">
               
                        <img src="~/img/portfolio/thumbnails/3.jpg" alt=""/>
                        <div class="portfolio-box-caption">
                            <div class="project-category text-white-50">
                                Category
                            </div>
                            <div class="project-name">
                                Restaurant Name
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a class="portfolio-box" href="img/portfolio/fullsize/4.jpg">
                     
                        <img src="~/img/portfolio/thumbnails/4.jpg" alt=""/>
                        <div class="portfolio-box-caption">
                            <div class="project-category text-white-50">
                                Category
                            </div>
                            <div class="project-name">
                                Restaurant Name
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a class="portfolio-box" href="img/portfolio/fullsize/5.jpg">
                      
                        <img src="~/img/portfolio/thumbnails/5.jpg" alt=""/>
                        <div class="portfolio-box-caption">
                            <div class="project-category text-white-50">
                                Category
                            </div>
                            <div class="project-name">
                                Restaurant Name
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a class="portfolio-box" href="img/portfolio/fullsize/6.jpg">
                   
                        <img src="~/img/portfolio/thumbnails/6.jpg" alt=""/>
                        <div class="portfolio-box-caption p-3">
                            <div class="project-category text-white-50">
                                Category
                            </div>
                            <div class="project-name">
                                Restaurant Name
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>
    <!-- Call to Action Section -->
    @*<section class="page-section bg-dark text-white">
        <div class="container text-center">
            <h2 class="mb-4">Free Download at Start Bootstrap!</h2>
            <a class="btn btn-light btn-xl" href="https://startbootstrap.com/themes/creative/">Download Now!</a>
        </div>
    </section>*@
    <!-- Contact Section -->
    <section class="page-section" id="contact">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8 text-center">
                    <h2 class="mt-0">Ready to order!</h2>
                    <hr class="divider my-4">
                    <p class="text-muted mb-5">Ready to order? Give us a call or send us email and we will give you the best service!</p>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4 ml-auto text-center">
                    <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
                    <div>+1 (202) 555-0149</div>
                </div>
                <div class="col-lg-4 mr-auto text-center">
                    <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
                    <!-- Make sure to change the email address in anchor text AND the link below! -->
                    <a class="d-block" href="mailto:contact@restaurant.com">contact@restaurant.com</a>
                </div>
            </div>
        </div>
    </section>
    <!-- Footer -->
    <footer class="bg-light py-5">
        <div class="container">
            <div class="small text-center text-muted">Copyright &copy; 2019 - Start Bootstrap</div>
        </div>
    </footer>
    <!-- Bootstrap core JavaScript -->

    <script src="~/vendor/jquery/jquery.min.js"></script>

    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Plugin JavaScript -->

    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <script src="~/vendor/magnific-popup/jquery.magnific-popup.min.js"></script>
    <!-- Custom scripts for this template -->
    <script src="~/Scripts/creative.min.js"></script>
</body>
</html>